import dask
import pandas as pd
import tensorflow as tf

from embeddings import BaseEmbedding


# BirdNet embedding class that inherits from BaseEmbedding and provides specific implementation for BirdNet.
class BirdnetEmbedding(BaseEmbedding):
    """
    BirdNet embedding model class for generating embeddings from audio data using the BirdNET model.

    This class extends the BaseEmbedding class and provides the specific implementation for loading
    the BirdNet model and processing audio datasets. BirdNet is used for analyzing and extracting
    features from audio clips, often for tasks such as species identification from bird calls.

    Inherited Attributes:
    ---------------------
    model_path : str
        Path to the pre-trained model used for generating embeddings.
    dask_client : dask.distributed.client.Client or None
        Optional Dask client for handling distributed task execution.

    Methods:
    --------
    load_model():
        Loads the BirdNet-specific model using TensorFlow.

    process(dataset_name: str, extension: str = '.wav', sampling_rate: int = 48000):
        Processes the audio dataset to generate embeddings using the BirdNet model.

    read_audio_dataset(dataset_name: str, extension: str = '.wav', sampling_rate: int = 48000):
        Inherited from BaseEmbedding. Reads the audio dataset from the file system and optionally
        processes it using Dask for parallel processing.
    """

    def __init__(self, model_path, dask_client: dask.distributed.client.Client or None = None):
        super().__init__(model_path, dask_client)
        self.model = None

    def load_model(self):
        """
        Load the BirdNet-specific model, using a TensorFlow SMLayer for generating embeddings.
        """
        # Load the BirdNet model from the specified path and set it up to generate embeddings.
        self.model = tf.keras.layers.TFSMLayer('assets/models/birdnet/V2.4/BirdNET_GLOBAL_6K_V2.4_Model',
                                               call_endpoint='embeddings')

    def process(self, dataset_name: str, extension: str = '.wav', sampling_rate: int = 48000):
        """
        Process the dataset using the BirdNet model to generate embeddings.

        :param dataset_name: Name of the dataset to process.
        :param extension: File extension for audio files (default is '.wav').
        :param sampling_rate: The sampling rate for the audio files (default is 48,000).
        :return: A pandas DataFrame containing the generated embeddings.
        """
        # Load the dataset of audio files into a DataFrame.
        self.data = self.read_audio_dataset(dataset_name, extension, sampling_rate)

        # Use the BirdNet model to predict the embeddings for the audio dataset.
        results = tf.keras.Sequential([self.model]).predict(self.data.batch(128), verbose=2)

        # Create a DataFrame containing the generated embeddings, indexed by the audio file.
        self.embeddings = pd.DataFrame(
            index=self.data.index,  # Use the index from the original dataset.
            data=results['embeddings']  # The embeddings generated by BirdNet.
        )

        # Return the generated embeddings.
        return self.embeddings
